# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninjas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninja_id', models.IntegerField()),
                ('dojo_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Dojos',
        ),
    ]
