# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_remove_dojos_dojo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dojos',
            new_name='Dojo',
        ),
        migrations.DeleteModel(
            name='Ninjas',
        ),
        migrations.AddField(
            model_name='ninja',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninas', to='dojo_ninjas.Dojo'),
        ),
    ]
