# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0004_auto_20171019_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='author',
            new_name='dojo',
        ),
    ]
