# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='making changes', max_length=255),
            preserve_default=False,
        ),
    ]
