# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
