# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20171024_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTrip',
            new_name='Trip',
        ),
    ]
