# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_auto_20171024_1342'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
                ('tripManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
