# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_auto_20171024_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='note',
        ),
    ]
