# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_remove_trip_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
