# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
