# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_auto_20171024_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_users', to='app_main.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_trip', to='app_main.User')),
            ],
            managers=[
                ('joinManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
