# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='app_main.Trip'),
        ),
    ]
