# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
            ],
            managers=[
                ('birthDayManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
